# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vjw1B6GOsRRA2hn_RCqLhAlZIa8OMmx
"""

import random

# Function to load words from file
def load_words(filename):
    """Load words from a text file and return a list of words."""
    with open(filename, 'r') as file:
        words = file.read().splitlines()  # Split lines into list
    return words

# Function to choose a random word
def choose_random_word(word_list):
    """Return a random word from the word list."""
    return random.choice(word_list).upper()  # Convert to uppercase for consistency


# Function to display hangman ASCII art
def display_hangman(wrong_count):
    """Show the hangman drawing based on wrong guesses."""
    stages = [
        """
          +---+
          |   |
              |
              |
              |
              |
        =========""",
        """
          +---+
          |   |
          O   |
              |
              |
              |
        =========""",
        """
          +---+
          |   |
          O   |
          |   |
              |
              |
        =========""",
        """
          +---+
          |   |
          O   |
         /|   |
              |
              |
        =========""",
        """
          +---+
          |   |
          O   |
         /|\\  |
              |
              |
        =========""",
        """
          +---+
          |   |
          O   |
         /|\\  |
         /    |
              |
        =========""",
        """
          +---+
          |   |
          O   |
         /|\\  |
         / \\  |
              |
        ========="""
    ]
    print(stages[wrong_count])


# Function to display current game state
def display_game_state(word, guessed_letters, wrong_letters, wrong_count, max_wrong):
    """Display the current word, guessed letters, wrong letters, remaining attempts, and hangman."""
    display_word = ' '.join([letter if letter in guessed_letters else '_' for letter in word])
    print("\nWord: ", display_word)
    print("Wrong letters: ", ' '.join(wrong_letters))
    print(f"Attempts remaining: {max_wrong - wrong_count}")
    display_hangman(wrong_count)


# Function to get player's guess
def get_player_guess(guessed_letters):
    """Prompt player for a letter and validate input."""
    while True:
        guess = input("Enter a letter: ").upper()
        if len(guess) != 1 or not guess.isalpha():
            print("Please enter a single letter (A-Z).")
        elif guess in guessed_letters:
            print("You already guessed that letter! Try another.")
        else:
            return guess


# Function to check if game is over
def check_game_over(word, guessed_letters, wrong_count, max_wrong):
    """Check if player has won or lost."""
    if all(letter in guessed_letters for letter in word):
        print(f"\nCongratulations! You guessed the word: {word}")
        return True
    if wrong_count >= max_wrong:
        print(f"\nGame Over! The word was: {word}")
        return True
    return False


# Main game function
def play_hangman():
    word_list = load_words("words.txt")
    word = choose_random_word(word_list)
    guessed_letters = []
    wrong_letters = []
    wrong_count = 0
    max_wrong = 6

    print("=== WELCOME TO HANGMAN ===")

    while True:
        display_game_state(word, guessed_letters, wrong_letters, wrong_count, max_wrong)
        guess = get_player_guess(guessed_letters + wrong_letters)

        if guess in word:
            print("Good guess!")
            guessed_letters.append(guess)
        else:
            print("Wrong letter!")
            wrong_letters.append(guess)
            wrong_count += 1

        if check_game_over(word, guessed_letters, wrong_count, max_wrong):
            display_hangman(wrong_count)
            break


# Program entry point
def main():
    play_hangman()
    while input("\nDo you want to play again? (Y/N): ").upper() == 'Y':
        play_hangman()
    print("Thanks for playing Hangman! Goodbye.")

if __name__ == "__main__":
    main()
